### ISSUE TITLE
Building for device

### ISSUE THREAD

**Issue by VGraupera** [cristianbica/CBSimulatorSeed#1]
Very nicely done. This is extremely useful for testing. However, why does it not build for device? I set the target to device and it gives errors whereas for simulator target it builds fine. Is there something about this that is Simulator specific?

**Comment by cristianbica** [comment]
This app was intended to be used on the simulator only and I'm going to leave it as it is. I put the code in main.m in a `#if TARGET_IPHONE_SIMULATOR` so it won't build on a device. I strongly suggest you don't run this on your device. For sure at a point in the future you'll replace all your contacts with the dummy ones and forget you activated iCloud sync and you'll permanently loose all your contacts. 
Anyway now that you have been warned open main.m and remove the `#if TARGET_IPHONE_SIMULATOR` and `#endif` parts :)

**Comment by VGraupera** [comment]
OK, thanks for explaining. I understand what you are saying. FYI, I am running it on a test device not connected to my real contacts in iCloud.
