### ISSUE TITLE
Pod install fail

### ISSUE THREAD

**Issue by lgarbo** [cristianbica/CBSimulatorSeed#2]
Even after update cocoapods, the command fails

**Comment by cristianbica** [comment]
what are the errors? Maybe it's related to http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/

**Comment by lgarbo** [comment]
Yes, resolved following the steps in the link.
Thanks for the tips.

**Comment by cristianbica** [comment]
cool
