### ISSUE TITLE
No visible @interface for 'NSArray' declares the selector 'each'

### ISSUE THREAD

**Issue by shmidt** [cristianbica/CBSimulatorSeed#3]
It seems that some pod is missing.

I get such error on build:
`No visible @interface for 'NSArray' declares the selector 'each:'`

**Comment by shmidt** [comment]
ObjectiveSugar is missing.

**Comment by cristianbica** [comment]
I'm using blockskit. Probably you updated to blockskit 2.0 where they namespaced all methods. Fixing now

**Comment by shmidt** [comment]
:) I installed ObjectiveSugar, and it worked also.

**Comment by cristianbica** [comment]
Fixed at dde947cf7a. updating the repo and running pod install should work
